version: '3.2'

services:
  front:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    networks:
      - elk

networks:
  elk:
    driver: bridge